"""change is_active to boolean

Revision ID: 2c71e6382275
Revises: b53a4f75af8d
Create Date: 2025-12-30 21:36:37.119340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c71e6382275'
down_revision: Union[str, Sequence[str], None] = 'b53a4f75af8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               postgresql_using="is_active = 1",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               postgresql_using="CASE WHEN is_active THEN 1 ELSE 0 END",
               existing_nullable=True)
    # ### end Alembic commands ###
